name: CI
'on':
- push
- pull_request
jobs:
  stages:
    runs-on: ubuntu-latest
    steps:
    - name: Run build
      run: build
    - name: Run test
      run: test
    - name: Run deploy
      run: deploy
  build-job:
    runs-on: ubuntu-latest
    steps:
    - name: Run echo "Comp
      run: echo "Compiling the code..."
    - name: Run echo "Comp
      run: echo "Compile complete."
  unit-test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Run echo "Runn
      run: echo "Running unit tests... This will take about 60 seconds."
    - name: Run sleep 60
      run: sleep 60
    - name: Run echo "Code
      run: echo "Code coverage is 90%"
  lint-test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Run echo "Lint
      run: echo "Linting code... This will take about 10 seconds."
    - name: Run sleep 10
      run: sleep 10
    - name: Run echo "No l
      run: echo "No lint issues found."
  deploy-job:
    runs-on: ubuntu-latest
    steps:
    - name: Run echo "Depl
      run: echo "Deploying application..."
    - name: Run echo "Appl
      run: echo "Application successfully deployed."
